### ISSUE TITLE
Are there any drawbacks to having a mutable store?

### ISSUE THREAD

**Issue by tangert** [BendingSpoons/katana-swift#149]
Just wondering. I noticed that there are no reducers in Katana and the store's properties are manipulated directly through actions. I'm between using ReSwift + ReactiveSwift and binding automatic UI changes that way, or Katana + Tempura, so I'm not really sure.

**Comment by bolismauro** [comment]
The store is not actually mutable since it is (supposed to be) a struct. The store class invokes the "update state" function which is a sort of reducer of the dispatched action.

In the very initial phases of Katana, we used to have an identical approach as Redux, and we had reducers. This caused huge issues in boilerplate code and so we decided to swift to this action+reducer approach.  So far the approach worked great, but we always look for improvements and better ways to handle the whole flow
