### ISSUE TITLE
Reduce boilerplate in Actions

### ISSUE THREAD

**Issue by okla** [BendingSpoons/katana-swift#155]
Current `Action` implementation leads to code like this
```swift
struct MyAction: Action {
  func updatedState(currentState: State) -> State {
    guard var state = currentState as? AppState else { 
      return currentState // Boilerplate
    } 
    // ... currentState changes
    return state // Boilerplate
  }
}
```
Wouldn't it be better to make it
```swift
struct MyAction: Action {
  func updateState(currentState: inout MyState) {
    // ... currentState changes
  }
}
```
This can be done in two simple steps:
1. Rename current `Action` to e.g. `BaseAction`
2. Implement `Action` as
```swift
protocol Action: BaseAction {
  associatedtype StateType: State
  func updateState(currentState: inout StateType)
}

extension Action {
  func updatedState(currentState: State) -> State {
    guard var state = currentState as? StateType else { fatalError("Wrong state type") }
    updateState(currentState: &state)
    return state
  }
}
```
`AsyncAction` can be simplified in the same way.

**Comment by bolismauro** [comment]
Hi!
Thanks for the input. You're completely right and we are aware of this problem. We decided 2 years ago to don't use that approach because of the issues with PAT and all the additional complications that they bring on the table. Moreover, it creates also some issues when it comes to Modularization and actions offered by libraries.

We are exploring different approaches for the next version of Katana, but in the meanwhile what we do it to use an additional protocol like this

```swift
protocol AppAction: Action {
  func updatedState(currentState: inout AppState)
}

extension AppAction {
  public func updatedState(currentState: State) -> State {
    guard var state = currentState as? AppState else {
      fatalError()
    }
    self.updatedState(currentState: &state)
    return state
  }
}
```

You can do the same thing for the `AsyncAction`. It is not perfect for sure, but it is quite handy

**Comment by okla** [comment]
>an additional protocol like this

Maybe it's better to encourage this approach by adding some `TypedAction: Action` protocol right to Katana instead of enforcing users to implement it by themselves.

Another place where boilerplate can be reduced a bit is `AsyncAction`: default implementations for `updatedStateFor...` methods can be added to protocol extension:
```swift
func updatedStateFor...(currentState: State) -> State {
  return currentState
}
```
>next version of Katana

Any hint about when it may be released?

**Comment by bolismauro** [comment]
It is actually a good idea :) Feel free to open a PR!

For the next version, we are starting to discuss it in these days. Since we have several different priorities, we will try to figure out how to prioritise them. If Katana ends up "winning", I expect this to happen in the next months (1/2 max).

About a year ago I wrote an evolution proposal, which was very ELM oriented and very radical. You can find it here
https://github.com/bolismauro/katana-evolution

It may be that we will use some of that ideas, but for sure it will become 100% compatible with the current version as we have several tens of apps that use Katana and update them all together would be crazy

**Comment by bolismauro** [comment]
As discussed, the [new katana experimental version](https://github.com/BendingSpoons/katana-swift/blob/experimental/) offers typed versions of the actions (state updaters and side effects actually, actions have been separated).

We are developing a couple of apps using this experimental version, so it is not really production ready yet.

Thanks a lot for the input!

**Comment by okla** [comment]
The link isn't working(

**Comment by bolismauro** [comment]
https://github.com/BendingSpoons/katana-swift/tree/experimental

sorry ;)

**Comment by okla** [comment]
Thanks, I'll give it a look!
