### ISSUE TITLE
Define and implement a fully declarative Table and Grid

### ISSUE THREAD

**Issue by lucaquerella** [BendingSpoons/katana-swift#51]
I'd like to prose a refactor of the table (and the grid) view.
What I propose is a declarative approach where the cell are passed to the table as children, similarly to what we have in a View Node.

Here is how I envision the creation of a Table:

```
   let table = Table(props: TableProps()) {
      return [
        View(props: ViewProps.build({
          $0.backgroundColor = .red
        })),
        View(props: ViewProps.build({
          $0.backgroundColor = .yellow
        }))
      ]
    }
```

The table should render the children managing the delegate of its native view. In general different native view should have different strategy when implementing the DrawableContainer protocol. The UIView should add its children as subviews (as it's already implemented), the UITableView should add the children using the native delegate. In the future we might want to add different strategies.

I believe this has two major advantages 

- it allows to use a Table in a much more convenient (and consistent with the rest of the framework)  way, without the need of implementing a delegate
- it allows us to keep a single node three, which allows to remove `mangedChildren` and to re-introduce alternative Drawable container (that we can use for debugging or profiling proposes) 
  
Here some useful resources:
- https://realm.io/news/altconf-benji-encz-uikit-inside-out-declarative-programming/
- https://github.com/jflinter/Dwifft

**Comment by smaramba** [comment]
The problem we are facing with this approach is that, when we need to add cells as children,  the `addChild(_ child: () -> DrawableContainer)` is called in the `DrawableContainer` that abstracts the `UITableView`. Unfortunately at this point we already have a child that is a `DrawableContainer` itself (backed by a `UITableViewCell`) while we would need a `NodeDescription` to instantiate the cell only when it's time. Otherwise if the table contains 1000 cells, we will have all the `UITableViewCell` instantiated even if only a bunch of them are visible.

**Comment by bolismauro** [comment]
Closed. Please re open it in the proper repo
